#!/usr/bin/env python3
"""Lint Persian copy and motion code for the mistakes that make Persian look "off".

usage:
  python3 lint_persian.py copy FILE_OR_TEXT [...]   check Persian copy (txt, md, json, tsx...)
  python3 lint_persian.py code PATH [...]           check code for Persian layout traps
Exit code 1 when something is found. Pure standard library.
From github.com/atmirrr/persian-motion-director (MIT, 5499640); canvas checks added for this repo.

Copy checks: Arabic ي/ك, Arabic-Indic digits, Latin digits glued to Persian, missing
half-spaces (می‌، ‌ها، ‌تر، ‌ای), zero-width space used as a half-space, English punctuation
and straight quotes in Persian, misplaced kashida (ـ), spacing around punctuation.
Code checks: letter-spacing near Persian, per-letter boxes, missing dir="rtl", lang="ar"
on Persian, scene-to-scene fade() transitions, default spring() configs.
Canvas (this repo): g.letterSpacing near Persian, per-character fillText, playful springs on Persian text.
"""
import os
import re
import sys

FA = r"؀-ۿ‌"
FA_LETTER = r"ء-يٱ-ۓۺ-ۿ"
RIGHT_JOINING = "اآأإدذرزژوؤةۀ"
VERB_STEMS = ("کن|شو|خواه|ده|توان|گیر|رو|آی|ساز|نویس|گوی|گو|بین|دان|رس|زن|خور|مان|کش|فرست|"
              "خوان|پرس|آور|بر|دار|گذار|یاب|پذیر|سوز|ریز|ترس|خند|گرد|افت|اندیش")
SUFFIXES = "ها|های|هایی|هایم|هایت|هایش|هایمان|هایتان|هایشان|تر|ترین"

COPY_RULES = [
    ("arabic-yeh", re.compile("ي"), "Arabic ي (U+064A): use Persian ی (U+06CC)"),
    ("arabic-kaf", re.compile("ك"), "Arabic ك (U+0643): use Persian ک (U+06A9)"),
    ("alef-maksura", re.compile(f"ى(?=$|[^{FA_LETTER}])"), "ى at a word end: Persian uses ی (U+06CC)"),
    ("arabic-digit", re.compile("[٠-٩]"), "Arabic-Indic digit: use Persian digits ۰–۹ (U+06F0–06F9)"),
    ("latin-digit", re.compile(f"[0-9]+(?=\\s?[{FA_LETTER}])|(?<=[{FA_LETTER}]\\s)[0-9]+"), "Latin digits beside Persian words: use Persian digits unless this is a version or code"),
    ("zwsp", re.compile("​"), "zero-width space (U+200B) does not stop joining: use the half-space ZWNJ (U+200C)"),
    ("mi-space", re.compile(f"(?:^|(?<=\\s))(ن?می) (?=[{FA_LETTER}])"), "می / نمی followed by a space: use a half-space (می‌)"),
    ("mi-glued", re.compile(f"(?:^|(?<=[\\s«(]))(ن?می)(?:{VERB_STEMS})"), "می / نمی glued to the verb: use a half-space (می‌)"),
    ("suffix-space", re.compile(f"(?<=[{FA_LETTER}]) (?:{SUFFIXES})(?=$|[\\s،.؟!:؛»)])"), "suffix after a full space: use a half-space (‌ها، ‌تر، ‌ترین)"),
    ("heh-ye-space", re.compile(f"(?<=ه) (?:ای|ایی)(?=$|[\\s،.؟!:؛»)])"), "ـه + ای after a space: write ـه‌ای with a half-space"),
    ("question-mark", re.compile(f"(?<=[{FA_LETTER}])\\s?\\?"), "English ? after Persian: use ؟"),
    ("comma", re.compile(f"(?<=[{FA_LETTER}]),"), "English comma after Persian: use ،"),
    ("semicolon", re.compile(f"(?<=[{FA_LETTER}]);"), "English semicolon after Persian: use ؛"),
    ("straight-quotes", re.compile(f'"(?=[{FA_LETTER}])|(?<=[{FA_LETTER}])"'), "straight quotes around Persian: use « »"),
    ("space-before-punct", re.compile("(?<=\\S) +(?=[،.؟!؛:])"), "space before punctuation"),
    ("double-space", re.compile("(?<=\\S)  +(?=\\S)"), "double space"),
]


def kashida_issues(line):
    out = []
    for m in re.finditer("ـ+", line):
        i = m.start()
        prev = line[i - 1] if i > 0 else ""
        nxt = line[m.end()] if m.end() < len(line) else ""
        if not prev or prev in " ‌" or prev in RIGHT_JOINING:
            out.append((i, "kashida", "ـ after a letter that does not join forward (or after a space/half-space)"))
        if nxt in "‌ ":
            out.append((i, "kashida", "ـ next to a half-space or space"))
        if prev == "ل" and nxt in "اآأإ":
            out.append((i, "kashida", "ـ inside لا breaks the required lam-alef ligature"))
    for word in re.finditer(f"[{FA}ـ]+", line):
        if len(re.findall("ـ+", word.group())) > 1:
            out.append((word.start(), "kashida", "more than one kashida in a word"))
    return out


def lint_copy_text(text, name):
    issues = []
    for ln, line in enumerate(text.splitlines(), 1):
        if not re.search(f"[{FA_LETTER}]", line):
            continue
        for code, rx, msg in COPY_RULES:
            for m in rx.finditer(line):
                issues.append((name, ln, m.start() + 1, code, msg))
        for col, code, msg in kashida_issues(line):
            issues.append((name, ln, col + 1, code, msg))
    return issues


CODE_EXT = (".js", ".jsx", ".ts", ".tsx", ".mjs", ".css", ".html", ".vue", ".svelte")


def lint_code_file(path):
    try:
        src = open(path, encoding="utf-8").read()
    except (UnicodeDecodeError, OSError):
        return []
    issues = []
    if "shape_persian.py" in src[:300] and "Generated by" in src[:300]:
        return []  # shaped glyph data, not text
    allowed = set(re.findall(r"lint-persian:\s*allow\s+([\w-]+)", src))
    # judge Persian presence on code and strings only, not comments
    code_only = re.sub(r"/\*.*?\*/", "", src, flags=re.S)
    code_only = re.sub(r"(?m)(^|[^:'\"`])//.*$", r"\1", code_only)
    has_fa = re.search(f"[{FA_LETTER}]", code_only) is not None
    lines = src.splitlines()

    def add(ln, code, msg):
        if code not in allowed:
            issues.append((path, ln, 1, code, msg))

    for ln, line in enumerate(lines, 1):
        if re.search(r"from ['\"]@remotion/transitions/fade['\"]|\bfade\(\)", line):
            add(ln, "scene-fade", "scene-to-scene fade(): move a camera or carry an object across instead")
        if re.search(r"\bspring\(\{\s*frame\s*,\s*fps\s*\}\)", line):
            add(ln, "default-spring", "default spring() overshoots ~16%: set config {stiffness: 100, damping: 16} or similar")
        if not has_fa:
            continue
        if re.search(r"letter-spacing\s*:|letterSpacing\s*[:=]", line) and re.search(rf"[{FA_LETTER}]|rtl|fa|letterSpacing\s*=", line):
            add(ln, "letter-spacing", "letter-spacing in a file with Persian: Chrome ignores it inside Persian words and other tools break joins; use kashida")
        if re.search(r"lang=['\"]ar['\"]", line):
            add(ln, "lang-ar", 'lang="ar" on Persian: use lang="fa" (digits and forms differ)')
    if has_fa:
        splits = re.search(r"\.split\(\s*['\"]{2}\s*\)|Array\.from\(|\[\.\.\.\w+\]|Segmenter\([^)]*grapheme", src)
        boxes = re.search(r"inline-block|inlineBlock|display:\s*['\"]?flex|display:\s*['\"]?grid", src)
        if splits and re.search(r"fillText\(|strokeText\(", src):
            add(src[: splits.start()].count("\n") + 1, "letter-filltext",
                "text split into characters in a canvas file: drawing Persian letter by letter shows isolated forms (measured 409 px vs 227 px for «بیشتر»); use M.fa.split (ZWJ) or shaped outlines")
        if boxes and splits:
            add(src[: splits.start()].count("\n") + 1, "letter-boxes",
                "text split into characters in a file that also makes inline-block/flex boxes: per-letter boxes break Persian joins (use shaped outlines or split_fa.js)")
        if not re.search(r"rtl", src) and re.search(f"['\"`>][^'\"`<]*[{FA_LETTER}]", code_only):
            add(1, "no-rtl", 'Persian text but no dir="rtl" anywhere in this file')
        for m in re.finditer(r"['\"]playful['\"]", src):
            add(src[: m.start()].count("\n") + 1, "playful-spring",
                "'playful' spring overshoots ~19%: never on Persian text (use calm/crisp; snappy ~1% only on UI)")
    return issues


def walk(paths):
    for p in paths:
        if os.path.isdir(p):
            for root, dirs, files in os.walk(p):
                dirs[:] = [d for d in dirs if d not in ("node_modules", ".git", "out", "dist", "build")]
                for f in files:
                    if f.endswith(CODE_EXT):
                        yield os.path.join(root, f)
        else:
            yield p


def main(argv):
    if len(argv) < 3 or argv[1] not in ("copy", "code"):
        print(__doc__)
        return 2
    mode, targets = argv[1], argv[2:]
    issues = []
    if mode == "copy":
        for t in targets:
            if os.path.exists(t):
                issues += lint_copy_text(open(t, encoding="utf-8").read(), t)
            else:
                issues += lint_copy_text(t, "<text>")
    else:
        for f in walk(targets):
            issues += lint_code_file(f)
    for name, ln, col, code, msg in issues:
        print(f"{name}:{ln}:{col}  {code}  {msg}")
    print(f"\n{len(issues)} issue(s)" if issues else "clean")
    return 1 if issues else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
